import { Inter } from 'next/font/google'
import './globals.css'
import Script from "next/script";
import { useSession } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script
        src="https://pg-web.nicepay.co.kr/v3/common/js/nicepay-pgweb.js"
        type="text/javascript"
      ></Script>
      <Script src="https://pay.nicepay.co.kr/v1/js/"></Script>
    </html>
  );
}
